apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-staging
  namespace: staging
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16

  bootstrap:
    initdb:
      database: n8n
      owner: n8n
      secret:
        name: postgres-staging-credentials

  storage:
    size: 5Gi
    storageClass: local-path
