apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n-staging
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: staging
  chart:
    spec:
      chart: ./apps/base/n8n
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    replicaCount: 1

    ingress:
      enabled: true
      className: nginx
      host: app.staging.local

    resources: {}

    autoscaling:
      enabled: false

    db:
      host: postgres-staging-rw.staging.svc.cluster.local
      secretName: postgres-staging-credentials

    n8n:
      encryptionKeySecret: n8n-encryption-key
